package pr115.rules.drl;

import jmr.s2db.tables.Event;
import jmr.s2db.event.*;
import jmr.pr115.schedules.run.*;
import jmr.util.hardware.*;
import jmr.util.*;
import com.google.gson.JsonObject;
import org.apache.commons.io.IOUtils;

import jmr.pr128.reports.Report;
import jmr.pr115.rules.drl.Simple;

dialect "mvel"


rule "Refresh_RecentEvents"
	when
		e : Event()
	then
		if ( ! SystemEvent.HEARTBEAT_HOUR.name().equals( e.getSubject() ) ) {
			Simple.doGenerateReport( Report.RECENT_EVENTS );
		}
end
