package pr115.rules.drl;

import jmr.s2db.tables.Event;
import jmr.s2db.event.*;
import jmr.pr115.schedules.run.*;
import jmr.util.hardware.*;
import jmr.util.*;
import com.google.gson.JsonObject;

import jmr.pr128.reports.Report;
import jmr.pr115.rules.drl.Simple;

dialect "mvel"


rule "Refresh_DeviceList_on_CLIENT_REGISTERED"
	when
		e : Event( // monitor client_registered
				getEventType() == EventType.SYSTEM, 
				getSubject().equals( SystemEvent.CLIENT_REGISTERED.name() )
			)
	then
		// Simple.doUpdateDevices();
		Simple.doGenerateReport( Report.DEVICES );
end


rule "Refresh_DeviceList_on_TimeEvent"
	when
		h : Heartbeat( getTimeUnit() == TimeUnit.HOURS )
	then
		// Simple.doUpdateDevices();
		Simple.doGenerateReport( Report.DEVICES );
end
