package pr115.rules.drl;

import jmr.s2db.tables.Event;
import jmr.s2db.event.*;
import jmr.pr115.schedules.run.*;
import jmr.util.hardware.*;
import jmr.util.*;
import com.google.gson.JsonObject;

import jmr.pr115.rules.drl.Simple;

dialect "mvel"


rule "RefreshDeviceList"
	when
		e : Event( // monitor client_registered
				getEventType() == EventType.SYSTEM, 
				getSubject().equals( SystemEvent.CLIENT_REGISTERED.name() )
			)
	then
		Simple.doUpdateDevices();
end
