package pr115.rules.drl;

import jmr.util.TimeUtil;
import jmr.pr115.rules.drl.Simple;
import jmr.pr115.schedules.run.Heartbeat;


dialect "mvel"


rule "Refresh Weather"
	when
		h : Heartbeat( getTimeUnit() == TimeUnit.HOURS )
		eval( TimeUtil.isHourOfDay( 
					4,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23 ) )
	then
		System.out.println( "Refreshing weather import.." );

		Simple.doRefreshWeather();
end
