package pr115.rules.drl;

import jmr.util.TimeUtil;
import jmr.pr115.rules.drl.Simple;
import jmr.pr115.schedules.run.Heartbeat;


dialect "mvel"


rule "Refresh Cloud Capture Thumbnails"
	when
		// h : Heartbeat( getTimeUnit() == TimeUnit.HOURS )
		h : Heartbeat( getTimeUnit() == TimeUnit.MINUTES )
		// eval( TimeUtil.isMinuteInHour( 0,10,20,30,40,50 ) )
		eval( TimeUtil.isMinuteInHour( 0,5,10,15,20,25,30,25,40,45,50,55 ) )
		// eval( TimeUtil.isMinuteInHour( 		 0, 2, 4, 6, 8, 
		//									10,12,14,16,18, 
		//									20,22,24,26,28, 
		//									30,32,34,36,38, 
		//									40,42,44,46,48, 
		//									50,52,54,56,58	) )
	then
		System.out.println( "Refreshing cloud thumbnails.." );

		Simple.updateDeviceThumbnails();
end
