//NOTE: do not add trailing semicolon (not required) 
package pr115.rules.drl;

import jmr.s2db.tables.Event;
import jmr.s2db.event.*;
import jmr.pr115.schedules.run.*;
import jmr.util.hardware.*;
import jmr.util.*;

// Cannot seem to actually use java.util.Map 
// (Map may already be declared and explicity referencing may not be working)

rule "TestEvent"
	//dialect "mvel" //NOTE: do not specify dialect here
	when
		e : Event( getEventType() == EventType.TIME )
	then
		System.out.println( "Test rule firing. Event: " + e.toString() );
end

/*
rule "TestJobWorker (any)"
	dialect "mvel"
	when
		j : JobWorker()
	then
		System.out.println( "Test rule firing. JobWorker: " + j.toString() );
end
*/

rule "TestJobWorker (RunTest)"
	dialect "mvel"
	when
		j : RunTest()
	then
		System.out.println( "Test rule firing. RunTest: " + j.toString() );
end
