package pr115.rules.drl

import jmr.s2db.tables.Event;
import jmr.s2db.event.EventType;
import jmr.pr115.schedules.run.JobWorker;
import jmr.pr115.schedules.run.RunTest;


rule "TestEvent"
	dialect "mvel"
	when
		e : Event( getEventType() == EventType.TIME )
	then
		System.out.println( "Test rule firing. Event: " + e.toString() );
end

rule "TestJobWorker (any)"
	dialect "mvel"
	when
		j : JobWorker()
	then
		System.out.println( "Test rule firing. JobWorker: " + j.toString() );
end

rule "TestJobWorker (RunTest)"
	dialect "mvel"
	when
		j : RunTest()
	then
		System.out.println( "Test rule firing. RunTest: " + j.toString() );
end
