package pr115.rules.drl;

import jmr.s2db.tables.Event;
import jmr.s2db.event.*;
import jmr.pr115.schedules.run.*;
import jmr.util.hardware.*;
import jmr.util.*;
import com.google.gson.JsonObject;

import jmr.pr115.rules.drl.Simple;

dialect "mvel"

global Boolean bCheckedHomeArrival;

rule "HomeArrival-Reset"
	when
		h : Heartbeat( getTimeUnit() == TimeUnit.HOURS )
		eval( TimeUtil.isHourOfDay( 15 ) )
	then
		// System.out.println( "Resetting home arrival trigger." );
		// bCheckedHomeArrival = false;
		Simple.resetHomeArrival();
end


rule "GaragePedDoor-RequestChargeStatus"
	when
		e : Event( // garage ped door open event
				getEventType() == EventType.INPUT, 
				getSubject().equals( HardwareInput.GARAGE_PED_DOOR_CLOSED_STOP.name() ),
				getValue().equals( "false" ) 
			)
		eval( TimeUtil.isWeekday() )
		eval( TimeUtil.isHourOfDay( 16,17,18,19,20,21 ) )
		// eval( not bCheckedHomeArrival ) // lets run this anyway
	then
		//System.out.println( "Garage pedestrian door opened (home arrival trigger)." );
		//if ( bCheckedHomeArrival ) return; // already home
		
		//bCheckedHomeArrival = true;
		
		// Simple.doCheckTeslaState( null );

		Simple.doHomeArrival();
end
