package jmr;

public enum SettingKey {

	TESLAMOTORS_USERNAME,
	TESLAMOTORS_PASSWORD,
	TESLA_LOW_BATTERY_THRESHOLD,
	
	NEST_USERNAME,
	NEST_PASSWORD,
	NEST_LOW_HUMIDITY_THRESHOLD,
	NEST_LOW_TEMPERATURE_THRESHOLD,
	
	;
}
